language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
install:
  - echo 'Hey Travis'
  - npm install
script:
  - npm test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
