language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
install:
  - npm install
script:
  - npm test
  - npm run build
  - npm publish
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
